language: node_js
node_js:
  - lts/*
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm run lint
  - npm run test-with-coverage
services: mongodb
env:
  global:
    - TEST_MONGODB_URI="mongodb://localhost:27017"
    - API_URL=/api
    - TEST_PORT=3000
    - ROOT_URL=jotain
    - SECRET=VERY_SECRET_THING
deploy:
  provider: heroku
  api_key:
    secure: iAHPAOXw/orqeV7P+wsh0vrjb3bohCO4R4jzx0QGUrrStQWILOt73pOWinO4cnXiO97eo7Z5muC5qyONb6LJHKMbev64eZZBcg7nulX9qMFh5GlrcNIl7Wxm8QSJV/S0+7gpG36bkNQ+c+D+QINWu/96IvDmgnNAljVZyl+6WX4iQSb6/o3ruQBVOLPCXHHJdqgruol50PC/ElTDPX6wgh2H0g+zMeJ46fYkZl/aMlV2lBLu4KBgAegaEH3mpkGtrLHn+0xkBBUn6yiNCsnqBwZ0hpWL/Z3HoT7Xp+oPJzOB6M4v2xTNdev7HWcltZiHdlsW5fTxyPhqpkitn0RjchbIR8VhuHrw9TBjtxg9eDtvYSQlWvjh3ldgdjEV53S3ziT9m0y/6AF8T2WM/GhiYeZ2eAbg8rbGIyIpRvvgvg5aY1itlonyOl1AXsb2fsUO65So29J94qQnSsERvppySTpw3UawqGQ9qo/KKk5n7wiGM3Dk72/ZHDF+XcdJrbj6VOCHV7GjDmxAT89mkk7nfWCG+xJjnrjYpzV0Co4NqftdDPe1FgI+lPqtQr5Hkh0p8OfJr12mVNEtoWVAaB5VktXHLVOmTKcXlp02znRG1hffgFDCi1AU0yvsZTXjFqBn+ar8fhbWGCPO6UcQESs6HKU1Uw8OQJ/ErRlsHojOSLM=
  app:
    master: sukeltaja
