language: node_js
node_js:
  - lts/*
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm run lint
  - npm run ci-coverage
services: mongodb
env:
  global:
    - TEST_MONGODB_URI="mongodb://localhost:27017"
    - API_URL=/api
    - TEST_PORT=3000
    - ROOT_URL=jotain
    - SECRET=VERY_SECRET_THING
deploy:
  provider: heroku
  api_key:
    secure: KPQU3KfvmxNQubN2dudXJWULbtr7Fainm3kSoJ603emmvC1+PnYLlQt7pcZNsVTZUf+uMf9NhjJqtWMf459P8leCZ428hkp2zDUgN3ywAcS8wsRuX4N3d1lwG9d7IBfZkhKkNu9rxao19lwknqCM91n2kjEie6SmM1GdCKiUlt7XpMImtBVLGh4+VkN1dsHMs5OuWv9vXwtTds7744407F6JiycJpwkg71hcWHl5qj4cAQ0lk+kNZtUxajVbPEzg9YXVczsCMOnDQRLC50rW/tplXLduV+6Ba5KY+4EVD06yWE2qooGKMULfPkQ9I7ZnRFr1pczk2aHsGUsAsRYzTaI6RBCpoDTG4yytd24kSnj+V0UaDcxTM3iP/NbXbWD9b0H0P8WbsYsmkQ8zveeKd92psaFvlozmyTyONkJk5T445TTmni8f+i+6y/vydKbQdDG12EH383glVBMggCto06GG5FIys1MPkXF7zYPas24O81AZzQSplHesF2brwNr9UwOku8iEKcSkILSicNRklCh8vpSPAqBNHe7Yvy6wIs4H/Ri6PLYACYPyCPqlyg1FRh11kWATmra9Y9SLnnDyhZTnARgwLR9hrHMAqQNJOC+EO1VLfBfgJC6ss0jhni/v4vlvO+voyMotURD/ckE5ST3xTqM4jqiHTxntaTCEnmA=
  app:
    master: sukeltaja
