GET http://localhost:3001/api/events/bo
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRhcnphbiIsImlkIjoiNWM3NDZlODc4ZmViMjAzMmZiNjk5ZTBjIiwiaWF0IjoxNTUzMDA5Nzk2fQ.jpsdyopm3cmrxEfVPxqMDnX8BrsqajKDqIr0NXAgIXI