PUT http://localhost:3001/api/events/5c7b4e24996be06baa32f576/add
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlcjIiLCJpZCI6IjVjNmU2OWQzY2U3ZjBlMTNhNGIxZmM4MCIsImlhdCI6MTU1MTYyNzMxN30.X6VnyBO1ye1zLTSp44B5KWOiUx6FmQ9f2Saysg-FDOs
