DELETE http://localhost:3001/events/5c52db3c39c2df5a6cd0a34e
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbGxlS2FwdGVlbmkiLCJpZCI6IjVjNTA1NjNmMmRhNzljMzFhMGE0ZTdmZSIsImlhdCI6MTU0ODc3MjIyOX0.2R_jraszM7emF0y6YmfXa3ZTrPE0Phdw795VdN0wCvw