GET http://localhost:3001/api/bousers/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1YzdlYTA0MzRkNWQyYzM5MDAwZGQxNzUiLCJpYXQiOjE1NTY3MjE0NzR9.MU_vInDcpFE-YGgdEL6biY6FKaS7QPK42X_NAI3cJPM