GET http://localhost:3001/api/events/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbGxlS2FwdGVlbmkiLCJpZCI6IjVjNTA1NjNmMmRhNzljMzFhMGE0ZTdmZSIsImlhdCI6MTU1MTYyNjIwNX0.DTXKO1OVAonpcHkwEvzAKN69RDQMthiUG_ELZcwdCnk
