POST http://localhost:3001/targets
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbGxlS2FwdGVlbmkiLCJpZCI6IjVjNTA1NjNmMmRhNzljMzFhMGE0ZTdmZSIsImlhdCI6MTU0OTk4NTYzMn0.DvNiRZTBktQJsxxK3R6_bwibYGQLRQ-P21P28EAA0hk

{
    "_id": "",
    "name": "Koiraluotojen soutuvene",
    "type": "Hylky",
    "depth": 7,
    "latitude": 60.1604,
    "longitude": 25.017483333,
    "hylyt_id": 7993,
    "hylyt_link": "http://www.hylyt.net/item/koiraluotojen-soutuvene/",
    "mj_id": "1000028676"
}