POST http://localhost:3001/users
content-type: application/json

{
    "_id": "",
    "username": "SannaSukeltaja",
    "password": "Salis321",
    "events": {
        "eventid": "5c497dccce853e2d84be1e28"
    },
    "__v": 0
}
