POST http://localhost:3001/events
content-type: application/json

{
    "_id": "",
    "content": "Hai puraisi jalkani irti",
    "startdate": "",
    "enddate": "",
    "user": "5c4b4ef22db3bf1bc4e1d381",
    "__v": 0
}
